name: Update Version on Commit

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run npm run update
        run: npm run update

      - name: Create and switch to new branch
        run: git checkout -b release

      - name: Commit and push changes
        env: 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global user.name "colour93"
          git config --global user.email "colour_93@furry.top"
          git add .
          git commit -m "Auto update data"
          git push origin release
